from turtle import *
penup()
goto(100,0)
goto(150,0)
pendown()
safhe = Screen()
safhe.bgcolor('lightblue')
spaceship = Turtle()
spaceship2 = Turtle()
spaceship.color('red')
spaceship2.color("blue")
dm = Turtle()
s = 1
PLAYER_1n = textinput("PLAYER_1","Enter your name :")
PLAYER_2n = textinput("PLAYER_2","Enter your name :")
def info(player,height,width,up,down,left,right,size,aa):
    ht()
    pensize(5)
    pencolor("purple")
    penup()
    goto(height,width)
    pendown()
    write(f"{player}\n {up}(up),{down}(down),{left}(left),{right}(right){aa}",False,"left",font=("Calibri",size,"normal"))
def draw_maze():
    global a, dm
    dm.pensize(10)
    dm.lt(180)
    dm.fd(50)
    dm.rt(90)
    dm.fd(50)
    dm.rt(180)
    dm.fd(50)
    dm.rt(90)
    dm.fd(100)
    dm.rt(90)
    dm.fd(150)
    dm.rt(180)
    dm.fd(150)
    dm.rt(90)
    dm.fd(100)
    dm.rt(90)
    dm.fd(250)
    dm.rt(90)
    dm.fd(100)
    dm.rt(90)
    dm.fd(50)
    dm.rt(180)
    dm.fd(50)
    dm.rt(90)
    dm.fd(100)
    dm.rt(90)
    dm.fd(130)
    dm.rt(180)
    dm.fd(130)
    dm.rt(90)
    dm.fd(50)
    dm.rt(90)
    dm.fd(200)
draw_maze()
dm.penup()
dm.goto(100,0)
dm.pendown()
info(PLAYER_1n,-250,280,"W","S","A","D",15,"")
draw_maze()
info(PLAYER_2n,100,280,"UP-ARROW","DOWN-ARROW","LEFT-ARROW","RIGHT-ARROW",10,"")
def travel():
    spaceship.forward(1)
    spaceship2.forward(1)
    x = round(spaceship.xcor())
    y = round(spaceship.ycor())
    x2 = round(spaceship2.xcor())
    y2 = round(spaceship2.ycor())
    print(x2, y2)
    if y2 == 0 :
        if 0<=x2<=150:
           penup()
           goto(0,-200)
           pendown()
           pencolor("red")
           shape("turtle")
           write(f"{PLAYER_2n} - WIN",True,"left",font=("Arial",30,"normal"))
           done()
           exit()
        if 150<=x2<=350:
           penup()
           goto(0,-200)
           pendown()
           pencolor("red")
           shape("turtle")
           write(f"{PLAYER_1n} - WIN",True,"left",font=("Arial",30,"normal"))
           done()
           exit()
    if y2 == 50 :
        if 0<=x2<=150:
           penup()
           goto(0,-200)
           pendown()
           pencolor("red")
           shape("turtle")
           write(f"{PLAYER_1n} - WIN",True,"left",font=("Arial",30,"normal"))
           done()
           exit() 
        if 250<=x2<=350:
           penup()
           goto(0,-200)
           pendown()
           pencolor("red")
           shape("turtle")
           write(f"{PLAYER_1n} - WIN",True,"left",font=("Arial",30,"normal"))
           done()
           exit()       
    if y2 == 150:
        if 100<=x2<=250:
           penup()
           goto(0,-200)
           pendown()
           pencolor("red")
           shape("turtle")
           write(f"{PLAYER_1n} - WIN",True,"left",font=("Arial",30,"normal"))
           done()
           exit()
        if 300<=x2<=350:
           penup()
           goto(0,-200)
           pendown()
           pencolor("red")
           shape("turtle")
           write(f"{PLAYER_1n} - WIN",True,"left",font=("Arial",30,"normal"))
           done()
           exit()
    if y2 == 250 :
        if 0<=x2<=250:
           penup()
           goto(0,-200)
           pendown()
           pencolor("red")
           shape("turtle")
           write(f"{PLAYER_1n} - WIN",True,"left",font=("Arial",30,"normal"))
           done()
           exit()
    if x2 == 350 :
        if 0<=y2<=250:
           penup()
           goto(0,-200)
           pendown()
           pencolor("red")
           shape("turtle")
           write(f"{PLAYER_1n} - WIN",True,"left",font=("Arial",30,"normal"))           
           done()
           exit()
    if x2 == 100 :
        if 0<=y2<=250:
           penup()
           goto(0,-200)
           pendown()
           pencolor("red")
           shape("turtle")
           write(f"{PLAYER_1n} - WIN",True,"left",font=("Arial",30,"normal"))
           done()
           exit()
    if y == 250 :
       if -250<=x<=0:
           penup()
           goto(0,-200)
           pendown()
           pencolor("red")
           shape("turtle")
           write(f"{PLAYER_2n} - WIN",True,"left",font=("Arial",30,"normal"))
           done()
           exit()
    elif y == 0 :
        if -250<=x<=0:
           penup()
           goto(0,-200)
           pendown()
           pencolor("red")
           shape("turtle")
           write(f"{PLAYER_2n} - WIN",True,"left",font=("Arial",30,"normal"))
           done()
           exit()

    elif x == -150:
        if 0<=y<=150:
           penup()
           goto(0,-200)
           pendown()
           pencolor("red")
           shape("turtle")
           write(f"{PLAYER_2n} - WIN",True,"left",font=("Arial",30,"normal"))
           done()
           exit()
        elif 200<=y<=250:
           penup()
           goto(0,-200)
           pendown()
           pencolor("red")
           shape("turtle")
           write(f"{PLAYER_2n} - WIN",True,"left",font=("Arial",30,"normal"))
           done()
           exit()
    elif x == -250 :
           penup()
           goto(0,-200)
           pendown()
           pencolor("red")
           shape("turtle")
           write(f"{PLAYER_2n} - WIN",True,"left",font=("Arial",30,"normal"))
           done()
           exit()
    elif x == -50 :
        if 0<=y<=50:
           penup()
           goto(0,-200)
           pendown()
           pencolor("red")
           shape("turtle")
           write(f"{PLAYER_2n} - WIN",True,"left",font=("Arial",30,"normal"))
           done()
           exit()
        elif 120<=y<=250:
           penup()
           goto(0,-200)
           pendown()
           pencolor("red")
           shape("turtle")
           write(f"{PLAYER_2n} - WIN",True,"left",font=("Arial",30,"normal"))
           done()
           exit()
    elif x == 0 :
        if 50<=y<=250:
           penup()
           goto(0,-200)
           pendown()
           pencolor("red")
           shape("turtle")
           write(f"{PLAYER_2n} - WIN",True,"left",font=("Arial",30,"normal"))
           done()
           exit()
        elif 0<=y<=50 :
           penup()
           goto(0,-200)
           pendown()
           pencolor("green")
           shape("turtle")
           write(f"{PLAYER_1n} - WIN",True,"left",font=("Arial",30,"normal"))
           done()
           exit()
    safhe.ontimer(travel, 13)
def becharkh1():
    spaceship.setheading(90)
def becharkh2():
    spaceship.setheading(180)
def becharkh3():
    spaceship.setheading(0)
def becharkh4():
    spaceship.setheading(270)
def becharkh11():
    spaceship2.setheading(90)
def becharkh22():
    spaceship2.setheading(180)
def becharkh33():
    spaceship2.setheading(0)
def becharkh44():
    spaceship2.setheading(270)
safhe.onkey(becharkh1, 'w')
safhe.onkey(becharkh1, 'W')
safhe.onkey(becharkh2, 'a')
safhe.onkey(becharkh2, 'A')
safhe.onkey(becharkh3, 'd')
safhe.onkey(becharkh3, 'D')
safhe.onkey(becharkh4, 's')
safhe.onkey(becharkh4, 'S')
safhe.onkey(becharkh11, 'Up')
safhe.onkey(becharkh22, 'Left')
safhe.onkey(becharkh33, 'Right')
safhe.onkey(becharkh44, 'Down')
safhe.listen()
spaceship.penup()
spaceship.goto(-215, 50)
spaceship.lt(90)
spaceship.pendown()
spaceship2.penup()
spaceship2.goto(150,200)
spaceship2.pendown()
travel()
done()